name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build site
        run: |
          if [ -z "${{ steps.pages.outputs.base_path }}" ]; then
            bundle exec jekyll build -d _site
          else
            bundle exec jekyll build -d "_site${{ steps.pages.outputs.base_path }}"
          fi
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # 경로 지정 (base_path가 있으면 _site+base_path, 없으면 _site)
          path: ${{ steps.pages.outputs.base_path && format('_site{0}', steps.pages.outputs.base_path) || '_site' }}


            
 #     - name: Setup Ads.txt
 #       run: |
 #         echo google.com, pub-8691553075583022, DIRECT, f08c47fec0942fa0 > ./_site/ads.txt
      
#      - name: Create CNAME file
#        run: |
#          echo www.yunseo.kim > ./_site/CNAME

#      - name: Test site
#        run: |
#          bundle exec htmlproofer _site \
#            \-\-disable-external \
#            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
              
